# Deliberate faults for tools/mutate.py: (name, exact snippet in the contract, replacement).
# Each must be caught by at least one test.
MUTATIONS = [
    ("DIES_WITH_IT does not become LAPSED",
     "fate = FATE_LAPSED if outcome == DIES_WITH_IT else FATE_STANDING", "fate = FATE_STANDING"),
    ("LAPSED stays invocable after the close",
     "return agreement_state != STATE_CLOSED or clause.fate == FATE_STANDING", "return True"),
    ("a proposal binds at once (no ratification)",
     "            state=C_PROPOSED,\n            invocation_count", "            state=C_RATIFIED,\n            invocation_count"),
    ("a proposed clause is invocable",
     "        if clause.state != C_RATIFIED:\n            return False", "        if clause.state in (C_DECLINED, C_WITHDRAWN):\n            return False"),
    ("ratification ignores the text hash",
     "        if given != clause.text_hash:", "        if False:"),
    ("text hash not normalized",
     "            text_hash=self._hash(normalized),", "            text_hash=self._hash(clean_text),"),
    ("the proposer may ratify",
     "        if caller == clause.proposer:\n            raise gl.vm.UserError(\"The other side must ratify or decline this clause\")\n        if clause.state != C_PROPOSED:\n            raise gl.vm.UserError(\"This clause is not awaiting ratification\")\n        if agreement.state",
     "        if clause.state != C_PROPOSED:\n            raise gl.vm.UserError(\"This clause is not awaiting ratification\")\n        if agreement.state"),
    ("the proposer may decline",
     "        if caller == clause.proposer:\n            raise gl.vm.UserError(\"The other side must ratify or decline this clause\")\n        if clause.state != C_PROPOSED:\n            raise gl.vm.UserError(\"This clause is not awaiting ratification\")\n        clause.state = C_DECLINED",
     "        if clause.state != C_PROPOSED:\n            raise gl.vm.UserError(\"This clause is not awaiting ratification\")\n        clause.state = C_DECLINED"),
    ("ratification allowed while closing",
     "        if agreement.state != STATE_LIVE:\n            raise gl.vm.UserError(\"This agreement is not live\")\n        given",
     "        if agreement.state == STATE_CLOSED:\n            raise gl.vm.UserError(\"This agreement is not live\")\n        given"),
    ("a stranger may act",
     "        if self._other_side(agreement, caller) == \"\":", "        if False:"),
    ("anyone may withdraw",
     "        if caller != clause.proposer:\n            raise gl.vm.UserError(\"Only the proposer may withdraw this clause\")", "        if False:\n            pass"),
    ("decline keeps the active slot",
     "        clause.state = C_DECLINED\n        agreement.active_count = u256(int(agreement.active_count) - 1)",
     "        clause.state = C_DECLINED"),
    ("withdraw keeps the active slot",
     "        clause.state = C_WITHDRAWN\n        agreement.active_count = u256(int(agreement.active_count) - 1)",
     "        clause.state = C_WITHDRAWN"),
    ("one side closes alone (request closes)",
     "        agreement.state = STATE_CLOSING\n", "        agreement.state = STATE_CLOSED\n"),
    ("the requester may confirm its own close",
     "        if caller == agreement.close_requested_by:\n            raise gl.vm.UserError(\"The other side must confirm the close\")", "        if False:\n            pass"),
    ("the other side may cancel the request",
     "        if caller != agreement.close_requested_by:\n            raise gl.vm.UserError(\"Only the side that asked to close may cancel\")", "        if False:\n            pass"),
    ("cancel does not reopen",
     "        agreement.state = STATE_LIVE\n        agreement.close_requested_by = \"\"",
     "        agreement.close_requested_by = \"\""),
    ("close does not void pending proposals",
     "                clause.state = C_VOID\n", "                pass\n"),
    ("proposals allowed while closing",
     "        if agreement.state != STATE_LIVE:\n            raise gl.vm.UserError(\"This agreement is not live\")\n        clean_text",
     "        if agreement.state == STATE_CLOSED:\n            raise gl.vm.UserError(\"This agreement is not live\")\n        clean_text"),
    ("the invoker may answer its own invocation",
     "        if self.invocation_by[slot] == caller:", "        if False:"),
    ("an invocation may be answered twice",
     "        if self.invocation_state[slot] != I_PENDING:", "        if False:"),
    ("acknowledge records CONTESTED",
     "        self._respond(clause_id_hex, index, note, I_ACKNOWLEDGED)", "        self._respond(clause_id_hex, index, note, I_CONTESTED)"),
    ("active cap off by one",
     "if int(agreement.active_count) >= MAX_ACTIVE_CLAUSES", "if int(agreement.active_count) > MAX_ACTIVE_CLAUSES"),
    ("slot cap ignored",
     " or int(agreement.slot_count) >= MAX_CLAUSE_SLOTS:", ":"),
    ("same agreement may be opened twice",
     "        if agreement_id in self.agreements:\n            raise gl.vm.UserError(\"This agreement already exists\")",
     "        if False:\n            raise gl.vm.UserError(\"This agreement already exists\")"),
    ("title not part of the agreement id",
     " + \"|\" + str(len(normalized_title)) + \"|\" + normalized_title)", ")"),
    ("the other side may be yourself",
     "        if other == caller:", "        if False:"),
    ("fail-safe flipped on unparseable output",
     "            if not isinstance(data, dict):\n                return {\"outcome\": SURVIVES}",
     "            if not isinstance(data, dict):\n                return {\"outcome\": DIES_WITH_IT}"),
    ("validator accepts any valid label",
     "                return str(mine.get(\"outcome\", \"\")).strip().upper() == leader_outcome", "                return True"),
    ("reserved token not checked in the text",
     "        if self._contains_reserved_token(clean_text):", "        if False:"),
    ("invocation cap off by one",
     "        if int(clause.invocation_count) >= MAX_INVOCATIONS:", "        if int(clause.invocation_count) > MAX_INVOCATIONS:"),
    ("text cap off by one",
     "        if len(cleaned) > MAX_TEXT_LENGTH:", "        if len(cleaned) > MAX_TEXT_LENGTH + 1:"),
]
