// Local ids must equal ids computed by the contract code (vectors generated by
// tests/contract/test_id_vectors.py on the real SDK Keccak256).
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { agreementId, clauseId } from "../../src/lib/ids.ts";
import { pyLen, pyNormalize, pyStrip } from "../../src/lib/pytext.ts";

const v = JSON.parse(readFileSync(new URL("./id-vectors.json", import.meta.url), "utf8"));

test("agreement id matches the contract", () => {
  assert.equal(agreementId(v.author, v.other), v.agreement_id);
  assert.equal(agreementId(v.author.toUpperCase().replace("0X", "0x"), v.other), v.agreement_id);
  assert.notEqual(agreementId(v.other, v.author), v.agreement_id);
});

test("clause ids match the contract, including whitespace edge cases", () => {
  assert.ok(v.clauses.length >= 7);
  for (const row of v.clauses) {
    assert.equal(pyNormalize(pyStrip(row.text)), row.normalized);
    assert.equal(pyLen(row.normalized), row.py_len);
    assert.equal(clauseId(v.agreement_id, row.text), row.clause_id, JSON.stringify(row.text));
  }
});

test("inner whitespace variants give the same clause id", () => {
  const a = clauseId(v.agreement_id, "Support stops on the closing date.");
  const b = clauseId(v.agreement_id, "  Support\tstops on  the\nclosing date. ");
  assert.equal(a, b);
});
